name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: Build C makefile projects
      run: cd c && make && cd ..
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install scons
      run: |
        python -m pip install --upgrade pip
        pip install scons
    - name: Build c/custom_characters
      run: cd c/custom_characters && scons
    -name: Run command
      run: cd c/custom_characters && ./transcribe encoding_example.csv hello github ci!
